# Generated by Django 5.2.7 on 2025-11-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='productos_interes',
            field=models.ManyToManyField(blank=True, related_name='clientes_interes', to='app_spa.productos'),
        ),
    ]
