# Generated by Django 5.2.7 on 2025-11-13 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spa', '0002_alter_clientes_productos_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_spa.servicios'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=10),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_spa.servicios'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_spa.productos'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_spa.productos'),
        ),
    ]
