# Generated by Django 5.2.7 on 2025-11-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spa', '0003_carritoitem_servicio_carritoitem_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
