# Generated by Django 5.2.7 on 2025-12-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spa', '0005_clientes_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
